### PR TITLE
[JENKINS-65161] remove commons-digester2 from core and upgrade plugins to commons-digester3

### PR DESCRIPTION
**Pull request by olamy**

### CODE REVIEW

**Comment by olamy** [comment]
see https://github.com/jenkinsci/jenkins/pull/5320

**Comment by marek-parfianowicz** [comment]
Thank you for your contribution, Olivier! 👍

**Comment by olamy** [comment]
@marek-parfianowicz no worries and thanks a lot for the merge.
Do you plan to cut a release soon?

**Comment by marek-parfianowicz** [comment]
> @marek-parfianowicz no worries and thanks a lot for the merge.
> Do you plan to cut a release soon?

I don't know yet. I think I shall also review and merge this PR https://github.com/jenkinsci/clover-plugin/pull/21. Is there any deadline for this?

**Comment by olamy** [comment]
The sooner the better 😀
More seriously end of this week or early next week sounds good and a reasonable target 
Thanks for looking at this!

**Comment by batmat** [comment]
To concur with Olivier: we would like to be able to merge https://github.com/jenkinsci/jenkins/pull/5320 as soon as reasonably possible. And when we do this, any unadjusted plugin will not work anymore on latest Jenkins version. 

And given we have 20+ PRs in flight, the more that are released, the more we can focus on what is left :-).

Thanks @marek-parfianowicz !

**Comment by marek-parfianowicz** [comment]
4.12.0 is released https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/clover/4.12.0/

**Comment by alecharp** [comment]
thank you @marek-parfianowicz

**Comment by batmat** [comment]
You're awesome @marek-parfianowicz ! Thank you very much! :-)

**Comment by pensionarchitects-ben** [comment]
After updating jenkins to v2.297 and using clover plugin version 4.12. I get the following error -> 

`11:01:08 ERROR: Step ‘Publish OpenClover coverage report’ aborted due to exception: 
11:01:08 java.lang.NoClassDefFoundError: org/apache/commons/digester/Digester
11:01:08 	at hudson.plugins.clover.CloverCoverageParser.createDigester(CloverCoverageParser.java:49)
11:01:08 	at hudson.plugins.clover.CloverCoverageParser.parse(CloverCoverageParser.java:68)
11:01:08 	at hudson.plugins.clover.CloverCoverageParser.parse(CloverCoverageParser.java:44)
11:01:08 	at hudson.plugins.clover.CloverPublisher.processCloverXml(CloverPublisher.java:198)
11:01:08 	at hudson.plugins.clover.CloverPublisher.performImpl(CloverPublisher.java:176)
11:01:08 	at hudson.plugins.clover.CloverPublisher.perform(CloverPublisher.java:141)
11:01:08 	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
11:01:08 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
11:01:08 	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:48)
11:01:08 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:808)
11:01:08 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:757)
11:01:08 	at hudson.model.Build$BuildExecution.post2(Build.java:179)
11:01:08 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:701)
11:01:08 	at hudson.model.Run.execute(Run.java:1936)
11:01:08 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
11:01:08 	at hudson.model.ResourceController.execute(ResourceController.java:100)
11:01:08 	at hudson.model.Executor.run(Executor.java:433)`

After searching a bit, I think the Digester import should be changed to -> org.apache.commons.digester3.Digester

@olamy @marek-parfianowicz

**Comment by alecharp** [comment]
@pensionarchitects-ben good call, sorry we didn't see this in the review here https://github.com/jenkinsci/clover-plugin/pull/24/files#diff-e68e032119e5e1812515b2efec5ab7819adc5fed91679673629ced271e5a0905L13

**Comment by olamy** [comment]
oh crapp sorry for that.

**Comment by olamy** [comment]
fixed with https://github.com/jenkinsci/clover-plugin/pull/25

**Comment by marek-parfianowicz** [comment]
I just released clover **4.12.1** with the fix.

**Comment by pensionarchitects-ben** [comment]
Thx for the quick responses and fix
